### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Dillon-MT** [MapWindow/MapWindow5#88]
Hi,

MW_v563 is crashing on startup on a Win10 computer.  Error message reads as follows:

An unhandled exception has occurred in the application.  There is no way to recover from it.  The application will be closed.  Please report the issue at http://mapwindow5.codeplex.com/workitem/list/basic.

Description: The type initializer for 'MW5.Api.Static.MapConfig' threw an exception.

Stack trace: 
   at MW5.Api.Static.MapConfig.set_ZoomToFirstLayer(Boolean value)
   at MW5.Helpers.MapInitializer.InitMapConfig()
   at MW5.Program.LoadConfig(IApplicationContainer container)
   at MW5.Program.Main()

Description: Retrieving the COM class factory for component with CLSID {80CDFEE0-576F-4141-906E-877638A2AEF3} failed due to the following error: 8007007e The specified module could not be found. (Exception from HRESULT: 0x8007007E).

Description: The type initializer for 'MW5.Api.Static.MapConfig' threw an exception.

Stack trace: 
   at MW5.Api.Static.MapConfig.set_ZoomToFirstLayer(Boolean value)
   at MW5.Helpers.MapInitializer.InitMapConfig()
   at MW5.Program.LoadConfig(IApplicationContainer container)
   at MW5.Program.Main()

Description: Retrieving the COM class factory for component with CLSID {80CDFEE0-576F-4141-906E-877638A2AEF3} failed due to the following error: 8007007e The specified module could not be found. (Exception from HRESULT: 0x8007007E).

Stack trace: 
   at MW5.Api.Static.MapConfig..cctor()

Thanks,
--
Dillon-MT

**Comment by Dillon-MT** [comment]
MW startup banner indicates it is version 5.6.4.26371.

I downloaded and installed the x64 version twice.

Win10 was a clean install 6 months ago.  Minimal software installed, MS office, QuickBooks, etc.

**Comment by Dillon-MT** [comment]
32 bit version seems to be working OK.

**Comment by pradvk** [comment]
same issue when building the project source dated 2021.05.17 even if it is target for x86

MapWindow.exe!MW5.Helpers.MapInitializer.InitMapConfig() Line 106

`System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'MW5.Api.Static.MapConfig' threw an exception.

  This exception was originally thrown at this call stack:
    MW5.Api.Static.MapConfig.MapConfig() in MapConfig.cs

Inner Exception 1:
FileNotFoundException: Retrieving the COM class factory for component with CLSID {80CDFEE0-576F-4141-906E-877638A2AEF3} failed due to the following error: 8007007e The specified module could not be found. (Exception from HRESULT: 0x8007007E).
`
